# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
# permalink:        pretty
permallink: /:year/:month/
#relative_permalinks: true

# Setup
title:            devwithpug
tagline:          'GitHub Blog'
description:      '공부하며 끄적이는 장소'
url:              'https://devwithpug.github.io'
baseurl:          ''

author:
  name:           'Choi Jungyu'
  url:            ''
plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 1
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  title: ':title'


github:
  repo:           https://github.com/devwithpug